package integrate

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestPreamble(t *testing.T) {
	p := Preamble("/abs/bin/erbrus", "review-kimi", "wt/feat")
	for _, want := range []string{
		"review-kimi",
		"wt/feat",
		"/abs/bin/erbrus msg send --report",
		"before the message text",
		"Do not start any work on your own",
	} {
		if !strings.Contains(p, want) {
			t.Errorf("preamble missing %q\n%s", want, p)
		}
	}
	if strings.Contains(p, "msg read") {
		t.Error("preamble must not tell agents to read channel history (removed by request)")
	}
}

func TestAssemblePrompt(t *testing.T) {
	got := AssemblePrompt("PRE", "TASK", "CTX")
	if got != "PRE\n\nTASK\n\nCTX" {
		t.Errorf("got %q", got)
	}
	if got := AssemblePrompt("PRE", "TASK", ""); got != "PRE\n\nTASK" {
		t.Errorf("empty context: %q", got)
	}
}

func TestHandoffContext(t *testing.T) {
	got := HandoffContext("webshop", "wt/feat", "impl-codex", "2026-08-27 10:00:00",
		"6 files changed", []string{"/data/artifacts/12/analysis.md"})
	for _, want := range []string{"webshop", "wt/feat", "impl-codex", "6 files changed", "/data/artifacts/12/analysis.md"} {
		if !strings.Contains(got, want) {
			t.Errorf("context missing %q\n%s", want, got)
		}
	}
}

func TestProviderHookClaude(t *testing.T) {
	dir := t.TempDir()
	args, err := ProviderHook("claude-code", dir, "/abs/erbrus")
	if err != nil {
		t.Fatal(err)
	}
	settings := filepath.Join(dir, "claude-settings.json")
	if args != "--settings "+settings {
		t.Errorf("args = %q", args)
	}
	data, err := os.ReadFile(settings)
	if err != nil {
		t.Fatal(err)
	}
	var v map[string]any
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("settings not valid JSON: %v\n%s", err, data)
	}
	if !strings.Contains(string(data), "'/abs/erbrus' msg send --system") {
		t.Errorf("stop hook must invoke the quoted absolute binary:\n%s", data)
	}
	if !strings.Contains(string(data), "Stop") {
		t.Errorf("no Stop hook in settings:\n%s", data)
	}
}

func TestProviderHookClaudeAllowsMsg(t *testing.T) {
	dir := t.TempDir()
	if _, err := ProviderHook("claude-code", dir, "/abs/erbrus"); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(filepath.Join(dir, "claude-settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	var got struct {
		Permissions struct{ Allow []string } `json:"permissions"`
	}
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatal(err)
	}
	if len(got.Permissions.Allow) != 1 || got.Permissions.Allow[0] != "Bash(/abs/erbrus msg *)" {
		t.Fatalf("allow = %v", got.Permissions.Allow)
	}
}

func TestProviderHookUnknownProvider(t *testing.T) {
	args, err := ProviderHook("junie", t.TempDir(), "/abs/erbrus")
	if err != nil || args != "" {
		t.Errorf("unknown provider must be a no-op, got %q, %v", args, err)
	}
}

func TestProviderHookCodex(t *testing.T) {
	t.Setenv("CODEX_HOME", t.TempDir()) // never touch the developer's ~/.codex
	dir := t.TempDir()
	args, err := ProviderHook("codex", dir, "/abs/erbrus")
	if err != nil {
		t.Fatal(err)
	}
	notifyScript := filepath.Join(dir, "notify.sh")
	if !strings.Contains(args, notifyScript) {
		t.Errorf("args must reference the notify script, got %q", args)
	}
	// codex parses the value as TOML: a quoted-string array, shell-quoted
	// as one argument.
	if !strings.Contains(args, `-c 'notify=["`+notifyScript+`"]'`) {
		t.Errorf("args must carry a TOML array, got %q", args)
	}
	if !strings.Contains(args, "-c sandbox_workspace_write.network_access=true") {
		t.Errorf("args must open sandbox networking for the erbrus API, got %q", args)
	}
	data, err := os.ReadFile(notifyScript)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "'/abs/erbrus' msg send --system") {
		t.Errorf("notify script must invoke the quoted absolute binary:\n%s", data)
	}
	// Check executable permission
	info, err := os.Stat(notifyScript)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode()&0o111 == 0 {
		t.Errorf("notify script must be executable, mode = %o", info.Mode())
	}
}

func TestProviderHookCodexWritesRules(t *testing.T) {
	home := t.TempDir()
	t.Setenv("CODEX_HOME", home)
	if _, err := ProviderHook("codex", t.TempDir(), "/abs/erbrus"); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(home, "rules", "erbrus.rules")
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`pattern = ["/abs/erbrus", "msg"]`, `pattern = ["erbrus", "msg"]`, `decision = "allow"`, "Generated by erbrus"} {
		if !strings.Contains(string(b), want) {
			t.Errorf("rules missing %q:\n%s", want, b)
		}
	}
	if strings.Count(string(b), "prefix_rule(") != 2 {
		t.Errorf("expected exactly two rules:\n%s", b)
	}
	// With codex installed, let its own policy engine parse the file.
	if codex, err := exec.LookPath("codex"); err == nil {
		out, err := exec.Command(codex, "execpolicy", "check", "--rules", path, "/abs/erbrus", "msg", "send", "--report", "x").CombinedOutput()
		if err != nil || !strings.Contains(string(out), `"decision":"allow"`) {
			t.Errorf("codex execpolicy check: %v\n%s", err, out)
		}
		out, _ = exec.Command(codex, "execpolicy", "check", "--rules", path, "/abs/erbrus", "serve").CombinedOutput()
		if strings.Contains(string(out), `"allow"`) {
			t.Errorf("serve must not be allowed by the rule:\n%s", out)
		}
	}
	// Same binary: untouched. New binary path: rewritten.
	if changed, err := ensureCodexRules(path, "/abs/erbrus"); err != nil || changed {
		t.Errorf("unchanged content rewritten: %v %v", changed, err)
	}
	if changed, err := ensureCodexRules(path, "/new/erbrus"); err != nil || !changed {
		t.Errorf("new path not written: %v %v", changed, err)
	}
	if b, _ := os.ReadFile(path); !strings.Contains(string(b), `pattern = ["/new/erbrus", "msg"]`) || strings.Contains(string(b), "/abs/erbrus") {
		t.Errorf("rewrite wrong:\n%s", b)
	}
}

func TestForwardToAgent(t *testing.T) {
	got := ForwardToAgent("/abs/erbrus", 7, "webshop", "general", "main", "/code/webshop",
		"claude", "2026-08-27 10:00:00", "auth is done", []string{"/data/artifacts/3/report.md"})
	for _, want := range []string{
		"forwarded from webshop / #general",
		"branch main",
		"worktree /code/webshop",
		"by claude at 2026-08-27 10:00:00",
		"auth is done",
		"attached file (read it yourself): /data/artifacts/3/report.md",
		`/abs/erbrus msg send --report --channel 7 'your reply'`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in:\n%s", want, got)
		}
	}
}

func TestChatReplySuffix(t *testing.T) {
	got := ChatReplySuffix("/abs/erbrus")
	if !strings.Contains(got, `/abs/erbrus msg send --report`) {
		t.Fatalf("missing reply command: %s", got)
	}
	if !strings.HasPrefix(got, "\n\n(") {
		t.Fatalf("suffix must be separated from the message body: %q", got[:8])
	}
}

func TestPreambleTeachesSafeQuoting(t *testing.T) {
	got := Preamble("/abs/erbrus", "claude", "general")
	for _, want := range []string{
		"/abs/erbrus msg send --report --md 'what you did'",
		"SINGLE quotes",
		"/abs/erbrus msg send --report --md - <<'EOF'",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("preamble missing %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, `--md "what`) {
		t.Fatal("preamble still shows double-quoted body")
	}
}
